name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the details below so we can investigate.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      description: Which part of the system is affected?
      multiple: true
      options:
        - Web App
        - Mobile App
        - Design Engine
        - Drawing Generator
        - BOM Engine
        - Cut List Engine
        - MEP Calculator
        - Catalogue Service
        - Procurement
        - Project Management
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Relevant environment details.
      placeholder: |
        - OS: Windows 11 / macOS 14 / Ubuntu 22.04
        - Browser: Chrome 120
        - Node: 20.10.0
        - Python: 3.11.6
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or error logs.
    validations:
      required: false
